BOX_IMAGE = "bento/ubuntu-18.04"
HOST_NAME = "ubuntu1804"
GO_VERSION = "1.17.6"

# privileged: true (root)
$pre_install = <<-SCRIPT
export DEBIAN_FRONTEND=noninteractive
echo ">>>> pre-install <<<<<<"
apt-get -qq update
apt-get -qq -y install gcc make pkg-config libseccomp-dev

echo ">>>> install go <<<<<<"
curl --stderr /dev/null -OL https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
echo 'PATH=$PATH:/usr/local/go/bin' | tee -a /etc/profile

echo ">>>>> install docker <<<<<<"
apt-get -qq -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl --stderr /dev/null -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get -qq update
apt-get -qq -y install docker-ce docker-ce-cli containerd.io
SCRIPT

Vagrant.configure("2") do |config|

 config.vm.define HOST_NAME do |subconfig|
   subconfig.vm.box = BOX_IMAGE
   subconfig.vm.hostname = HOST_NAME
   subconfig.vm.network :private_network, ip: "192.168.100.2"
   subconfig.vm.provider "virtualbox" do |v|
     v.memory = 1536
     v.cpus = 2
   end
   subconfig.vm.provision "shell", privileged: true, env: {"GO_VERSION"=>GO_VERSION}, inline: $pre_install
 end

end